baseURL = 'https://vroom.baycountrydrivingschool.com/'
languageCode = 'en-us'
title = 'Vroom! The Blog for Bay Country Driving School'
theme = "bcds"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

ignoreLogs = ['warning-goldmark-raw-html']

[taxonomies]
  tag = "tags"
  category = "categories"


[params]
    address     = "8673 Commerce Dr #11, Easton, MD 21601"
    phone       = "(410) 822-4411"
    email       = "info@baycountrydrivingschool.com"
    lastUpdated = "July, 2025"
    credit = 'DMX Studio'

[caches]
  [caches.images]
    dir = ':cacheDir/images'

